import type { Metadata } from "next";
import "./styles/globals.css";

import { DataContextProvider } from "@/context/dataContext";
import NavLayout from "./components/navLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
          <DataContextProvider>
            <body>
              <NavLayout></NavLayout>
              {children}
            </body>
          </DataContextProvider>
    </html>
  );
}
