import type { Metadata } from "next";
import "./styles/globals.css";

import { DataContextProvider } from "@/context/dataContext";
import { AuthProvider } from "@/context/AuthContexto";
import NavLayout from "./components/navLayout";

import { useLogin } from "@/hooks/useLogin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <AuthProvider value={{ user: null }}>
          <DataContextProvider>
            <body>
              <NavLayout></NavLayout>
              {children}
            </body>
          </DataContextProvider>
      </AuthProvider>
    </html>
  );
}
